//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GenericList
{
	public virtual int count
	{
		get;
		set;
	}

	public virtual IEnumberable IEnumberable
	{
		get;
		set;
	}

	public virtual void AddObject()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveObject()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

}

